kumuluzee:
  name: rso-uporabnik
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/rso-uporabnik
    connection-url: jdbc:postgresql://192.168.99.100:5432/rso-uporabnik
    username: postgres
    password: postgres
    max-pool-size: 20