apiVersion: apps/v1
kind: Deployment
metadata:
  name: uporabnik-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uporabnik
  template:
    metadata:
      labels:
        app: uporabnik
    spec:
      containers:
      - image: bostjan15/rsouporabniki:latest
        name: album
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: gcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://sl-eu-gb-p02.dblayer.com:16079/compose
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          value: admin
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          value: MVAFTGCOCZMSODPN
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: uporabnik
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    protocol: TCP
    targetPort: server
  selector:
    app: uporabnik
